@update
function us:processRegisteredQueries(q, del, ins) {
  for (select ?callback ?query ?trigger from <##SUBSCRIBERS_GRAPH_IRI##> where { ?x a us:Subscription ; us:callback ?callback ; us:query ?query ; us:trigger ?trigger . }) {
    xt:print(?trigger);
    if (sandbox:invokeTrigger(?trigger, del, ins)) {
      xt:print("Triggered, performing query...");
      dispatcher:notifySubscriber(?callback, xt:sparql(?query));
    } else {
      xt:print("Not triggered")
    }
  }
}